### ISSUE TITLE
Affective Features code

### ISSUE THREAD

**Issue by Tandon-A** [UttaranB127/STEP#2]
Hello, 

I read this paper recently and wanted to try my hands on it. Thank you for providing the code for the same.

How to obtain the affective features of a custom dataset? 

Regards
Abhishek

**Comment by UttaranB127** [comment]
Hello Abhishek,

Thanks a lot for your question! I have added a set of scripts under `compute_aff_features` to generate affective features for 16-joint pose sequences. You can go through `compute_features.py` to check how the pose sequence is used. You can either modify your pose sequence to match `compute_features.py`, or modify `compute_features.py` to match your pose sequence (I would recommend the latter since the former can introduce a lot of unintended noise in computations).

**Comment by Tandon-A** [comment]
Thank you for providing immediate assistance. I will look into the provided code. 

Regards 
Abhishek
