### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by zsh2000** [UttaranB127/STEP#7]
Hi,

Thanks for the code and dataset you have offered! I find myself really interested in your work!

I have some questions about the dataset as follows:

1. I want to visualize the motion sequences in the dataset, but I find that the root joint (joint #0) is not at the origin of the coordinates, which is different from the ELMD dataset setting. (visualization in the first figure below) Also, when I try relocating the root joint to the origin, the scales and visual angles of the gaits vary a lot. (visualization in the second figure below) I wonder whether I need to do some preliminary works before visualizing the gaits.

2. The synthetic gaits in the dataset seem a little strange. After performing visualization, it looks like the person is dragging his/her legs rather than walking.

3. I wonder how the emotion labels are annotated. Are they annotated by pretrained models, or annotated manually?

Many thanks and best wishes!
Shuhong

<img width="739" alt="没用" src="https://user-images.githubusercontent.com/52485301/118817777-2ce31300-b8e6-11eb-97dd-d1d5d05c4282.png">

<img width="787" alt="elmd" src="https://user-images.githubusercontent.com/52485301/118817710-1937ac80-b8e6-11eb-875b-2d3ce62fa569.png">

**Comment by UttaranB127** [comment]
Hi Shuhong,

Many thanks for your interest in our work!

1. We visualized the gaits in a Unity environment. I am sharing the Unity project with you [here](https://drive.google.com/file/d/1qrCe1Rz15nUyN5BTZDKGKoQzb63ewYOo/view?usp=sharing). In order to visualize, you have to create a new Unity project with the given Assets, attach the `RGB.cs` script to the GameObject, and run the Unity project. The `RGB.cs` script reads in the`.h5` files of the gaits.
2. Yes, the synthetic gaits are not the best. We improved on this in our future projects, especially in https://github.com/UttaranB127/GeneratingEmotiveGaits.
3. The emotions were annotated manually by domain experts.

Best regards,
Uttaran

**Comment by zsh2000** [comment]
Hi,

Thanks so much for your quick reply!! I will try it!

In addition, I wonder whether the experts do the annotation on the raw skeleton data, or they do it after the skeletons are rendered to RGB videos (or the AR environment).

Best regards,
Shuhong

**Comment by UttaranB127** [comment]
They actually did it on the raw RGB videos of the participants, from which we later extracted the skeletons and rendered those skeletons in Unity. Unfortunately, we cannot share the raw RGB videos at this point due to confidentiality constraints.

**Comment by zsh2000** [comment]
Thank you so much!! I get it!
